
help:
	@echo "# C++ ~ GCC 7.4.0, 1+2: ~0.02s"
	@echo "FILE=... make run-cpp"

run-cpp:
	../bin/day05 ${FILE} 1 | grep OUTPUT
	../bin/day05 ${FILE} 5 | grep OUTPUT

run-cpp-1:
	../bin/day05 ${FILE} 1

run-cpp-2:
	../bin/day05 ${FILE} 5

.PHONY: help run-cpp-1 run-cpp-2 run-cpp
