FILE ?= input.txt
PY ?= python3


help:
	@echo "# Python 3.6.8, 1: TBD"
	@echo "# Python 3.6.8, 2: TBD"
	@echo "FILE=... make run-python"

run-python:
	${PY} day18.py ${FILE}

.PHONY: help run-python
