FILE ?= input.txt


help:
	@echo "# C++, 1: ~0.51s"
	@echo "# C++, 2: ~58s"
	@echo "FILE=... make run-cpp"

run-cpp:
	../bin/day19 ${FILE}
	../bin/day19 ${FILE} 2

run-cpp-1:
	../bin/day19 ${FILE}

run-cpp-1:
	../bin/day19 ${FILE} 2

.PHONY: help run-cpp run-cpp-1
