FILE ?= input.txt


help:
	@echo "# C++, 1: ~0.4s"
	@echo "# C++, 2: ~70s"
	@echo "FILE=... make run-cpp"

run-cpp:
	../bin/day11 ${FILE}
	../bin/day11 ${FILE} 2

run-cpp-1:
	../bin/day11 ${FILE}

run-cpp-2:
	../bin/day11 ${FILE} 2

.PHONY: help run-cpp run-cpp-1 run-cpp-2
