FILE ?= input.txt


help:
	@echo "# C++, 1: ~0.14s"
	@echo "FILE=... make run-cpp"

run-cpp:
	../bin/day17 ${FILE}
	../bin/day17 ${FILE} 2 file

run-cpp-1:
	../bin/day17 ${FILE}

.PHONY: help run-cpp run-cpp-1
